/*
HACKERS (HACKER_ID, NAME)
DIFFICULTY (DIFFICULTY_LEVEL, SCORE)
CHALLENGES (CHALLENGE_ID, HACKER_ID, DIFFICULTY_LEVEL)
SUBMISSIONS (SUBMISSION_ID, HACKER_ID, CHALLENGE_ID, SCORE)  
*/
SELECT H.HACKER_ID, H.NAME
FROM HACKERS H
INNER JOIN SUBMISSIONS S
ON H.HACKER_ID = S.HACKER_ID
INNER JOIN CHALLENGES C
ON S.CHALLENGE_ID = C.CHALLENGE_ID
INNER JOIN DIFFICULTY D
ON C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
WHERE S.SCORE = D.SCORE AND C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(H.HACKER_ID) > 1
ORDER BY COUNT(H.HACKER_ID) DESC, H.HACKER_ID ASC;
