/*
OCCUPATIONS(NAME, OCCUPATION)
*/
SELECT MIN(IF(OCCUPATION = 'Doctor',NAME,NULL)),
  MIN(IF(OCCUPATION = 'Professor',NAME,NULL)),
  MIN(IF(OCCUPATION = 'Singer',NAME,NULL)),
  MIN(IF(OCCUPATION = 'Actor',NAME,NULL)) 
FROM(
    SELECT ROW_NUMBER() OVER(PARTITION BY OCCUPATION
                             ORDER BY NAME) AS ROW_NUM,
            NAME, 
            OCCUPATION
    FROM OCCUPATIONS) AS AUX
GROUP BY ROW_NUM; 
